[feature] Unified documentation website #107
Closes #107

---------

Co-authored-by: Federico Capoano <f.capoano@openwisp.io>

diff --git a/run-qa-checks b/run-qa-checks
--- a/run-qa-checks
+++ b/run-qa-checks
@@ -10,16 +10,27 @@ openwisp-qa-check \
     --skip-isort \
     --skip-flake8 \
     --skip-black \
-    --skip-checkrst
-
-./check_line_length.py
+    --skip-checkendline
 
 echo ''
-echo 'Checking documentation build status'
-make html
+echo 'Build documention to look for syntax errors'
+make build
 
 # check for broken link
+cd _build/
 python -m http.server 8001 &> /dev/null & pid=$!
 sleep 4
-pylinkvalidate.py http://localhost:8001/_build/
+BASE_URL="http://localhost:8001"
+if [ -n "${PRODUCTION:-}" ]; then
+    BASE_URL="$BASE_URL/docs/__new__"
+fi
+pylinkvalidate.py "$BASE_URL/dev/" \
+    -w 4 -m process
 kill "${pid}"
+
+# Verify PDFs are valid
+for pdf in _build/*/*.pdf; do
+    if ! pdfinfo "$pdf" &> /dev/null; then
+        echo "$pdf is broken"
+    fi
+done
